server:
  port: 8080

spring:
  spring:
    servlet:
      multipart:
        max-file-size: 50MB
        max-request-size: 50MB
  thymeleaf:
    cache: false
  profiles:
    include:
#      - dev
#      - oauth
      - local
      - local-oauth
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

