server:
  port: 8080

spring:
  thymeleaf:
    cache: false
  profiles:
    include:
#      - dev
#      - oauth
      - local
      - local-oauth
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher